/*! @file Router model
 *
 *  vim:set ts=8 sw=8 filetype=cpp noai nosi cin nu noet nolbr sm sbr=">" ff=unix syntax=cpp noic nowrap:
 *  $Id$
 */

#ifndef __FTPORT_H__
#define __FTPORT_H__

#include "port.h"

const unsigned defaultthreshold=4;

/*! A port in a node. Port is dumb that it just pass on a packet to its
 *  neighbour. No packet would be generated by a port. */
class ftport : public port
{
protected:
	unsigned threshold;
public:
	ftport(node* _parent,unsigned _IP,double _speed,
		unsigned _threshold=defaultthreshold, unsigned _maxqsize=defaultmaxqsize);
	virtual ~ftport();
	static port* factory(node* _parent, unsigned _IP, double _speed, unsigned _maxqsize=defaultmaxqsize);
				//< Factory method to create new port
	virtual void enqueue(packet* p);
				//< Enqueue a packet to the buffer
};

#endif
